// Generated by grid_recipe.py. Edit the JSON source and render again.
#set page(width: 280mm, height: auto, margin: 8mm, fill: rgb("#f5f4ef"))
#set text(font: "Alegreya", size: 10.5pt, fill: rgb("#202820"))
#set par(leading: 0.55em)

#let border = rgb("#879287")
#let title-fill = rgb("#f0eee5")
#let prep-fill = rgb("#dff1e3")
#let ingredient-fill = rgb("#fffef9")
#let action-fill = rgb("#f7f8f3")
#let waiting-fill = rgb("#fbfcf8")
#let ingredient-names = ("unsalted butter", "sugar", "eggs", "vanilla extract", "all-purpose flour", "cocoa powder", "baking soda", "table salt",)

#let ingredient(amount, name) = context {
  let name-width = calc.max(
    ..ingredient-names.map(name => measure(strong(name)).width)
  )
  if amount == "" { strong(name) }
  else {
    grid(
      columns: (name-width, 1fr),
      column-gutter: 1em,
      align: (left, right),
      strong(name),
      amount,
    )
  }
}

#block(
  width: 100%,
  fill: white,
  stroke: 1pt + border,
  radius: 8pt,
  clip: true,
  inset: 0pt,
)[
  #table(
    columns: (34%, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr),
    stroke: 0.55pt + border,
    table.cell(x: 0, y: 0, fill: title-fill, align: left + horizon, inset: (x: 10pt, y: 9pt), colspan: 7)[#text(size: 17pt, weight: "bold", "Classic Cocoa Brownies")],
    table.cell(x: 0, y: 1, fill: prep-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), colspan: 7)[#text("Butter and flour an 8 × 8-inch pan")],
    table.cell(x: 0, y: 2, fill: prep-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), colspan: 7)[#text("Preheat oven to 350°F (175°C)")],
    table.cell(x: 0, y: 3, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("4 oz (115 g)", "unsalted butter")],
    table.cell(x: 1, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[#text("Melt")],
    table.cell(x: 0, y: 4, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1 cup (200 g)", "sugar")],
    table.cell(x: 2, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 2)[#text("Cream")],
    table.cell(x: 0, y: 5, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("2 large", "eggs")],
    table.cell(x: 3, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 3)[#text("Beat in")],
    table.cell(x: 0, y: 6, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1 tsp", "vanilla extract")],
    table.cell(x: 4, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 4)[#text("Mix")],
    table.cell(x: 0, y: 7, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1/2 cup (80 g)", "all-purpose flour")],
    table.cell(x: 0, y: 8, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1/3 cup (80 g)", "cocoa powder")],
    table.cell(x: 0, y: 9, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1/4 tsp", "baking soda")],
    table.cell(x: 0, y: 10, fill: ingredient-fill, align: left + horizon, inset: (x: 8pt, y: 7pt))[#ingredient("1/4 tsp", "table salt")],
    table.cell(x: 1, y: 7, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 4)[#text("Whisk together")],
    table.cell(x: 5, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 8)[#text("Fold in")],
    table.cell(x: 6, y: 3, fill: action-fill, align: center + horizon, inset: (x: 8pt, y: 7pt), rowspan: 8)[#text("Bake at 350°F (175°C) for 30–40 minutes")],
    table.cell(x: 1, y: 4, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 1, y: 5, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 5, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 1, y: 6, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 6, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 3, y: 6, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 7, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 3, y: 7, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 4, y: 7, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 8, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 3, y: 8, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 4, y: 8, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 9, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 3, y: 9, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 4, y: 9, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 2, y: 10, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 3, y: 10, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
    table.cell(x: 4, y: 10, fill: waiting-fill, align: center + horizon, inset: (x: 8pt, y: 7pt))[],
  )
]
